### ISSUE TITLE
Caret position after setOptions

### ISSUE THREAD

**Issue by ShaMan123** [arnog/react-mathlive#4]
When react renders the component it loses caret position (due to an update I guess) and the caret is rendered at the end of the `mathfield`, probably due to internal mathlive update logic. 
The question is what logic and how to handle it accordingly.
I think it's important to solve this, e.g. Editing a `mathfield` while it updates some option will throw the caret to the end, making editing quite unstable.

**Comment by ShaMan123** [comment]
this seems to be caused by mathfield.

**Comment by ShaMan123** [comment]
Please see example app

**Comment by arnog** [comment]
Fixed in mathlive main branch

**Comment by arnog** [comment]
Fixed in mathlive@0.60.1
