### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by ramon-adan** [arnog/react-mathlive#8]
Is there a way to support MathLive on SSR?, I get this error; 

ReferenceError: document is not defined
    at /node_modules/mathlive/dist/mathlive.min.js:2:912106
    at /node_modules/mathlive/dist/mathlive.min.js:2:69
    at Object.<anonymous> (/node_modules/mathlive/dist/mathlive.min.js:2:209)

I'm using the latest version of Mathlive 0.72.1

**Comment by hobo1618** [comment]
Hey I ran into the same issue. Are you using NextJS? If so you can fix the issue by creating a component and then importing that component dynamically. The `MathView` component therefore won't be rendered on the server (it's a web component under the hood which extends HTMLElement), but the rest of your app can be. Basically this workaround lazyloads the web component. Here's [an example repo](https://github.com/hobo1618/next-math-view-app) that demonstrates the idea.

**Comment by Mopiel** [comment]
We have the same problem on 0.77.0 :(

**Comment by arnog** [comment]
The current version of MathLive is 0.95.5.

**Comment by Mopiel** [comment]
@arnog It works with 0.95.5. We just need to change our current logic to adjust to the latest version. Thank you 👍
